# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxswiftpractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Pods for rxswiftpractice

  target 'rxswiftpracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxswiftpracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
